#!/bin/bash
# A simple docker pull local repository script

localServer="localhost"
port=5000
daemonFile="/etc/docker/daemon.json"
display_usage() { 
	echo -e "Pull given image to a repository server \n"
	echo -e "Usage:\n$0 [options] <saved_image>\n" 
	echo -e " <saved_image>\t\t\t The image to pull from Repository" 
	echo -e " -p [--port]\t\t\t Reposityr port. Default: ${port}" 	
	echo -e " -s [--server]\t\t\t Reposityr server. Default: ${localServer}" 	
	echo -e " -h [--Help]\t\t\t Display Help" 	
	echo -e "\nExample: $0 -p ${port} -s ${localServer} mysql:8.0"
}

# Check params
if [  $# -le 0 ] 
then 
	display_usage
	exit 1
fi
while getopts p:s:t:h option
do
    case "${option}" in
        p) port=${OPTARG};;
        s) localServer=${OPTARG};;
        h) display_usage
            exit;;
        \?)  echo -e "\nInvalid option: -${OPTARG}" >&2
            exit;;
    esac
done
image=${*: -1:1}
echo -e "\nPulling from repository server"
docker pull ${localServer}:${port}/$image
if [ $? -ne 0 ]; then
    echo -e "\nWhitelisting ${localServer}:${port} to $daemonFile"
    jq --version > /dev/null 2>&1; jq=$?;
    if [ $jq -ne 0 ]; then
        echo "Installing jq..."
        apt-get install jq -y > /dev/null 2>&1; is_ubuntu=$?;
        if [ $is_ubuntu -ne 0 ]; then
            yum install jq -y > /dev/null 2>&1; is_centos=$?;
        else
            echo -e "\nPlease add this following to $daemonFile"
            echo "{ \"insecure-registries\":[ \"${localServer}:${port}\" ] }"
            echo -e "\nPulling failed..."
        fi
    else
        echo "Updating $daemonFile"
        cat $daemonFile > /dev/null 2>&1; is_exists=$?;
        if [ $is_exists -ne 0 ]; then
            echo -e "\nCreating daemon.json"
            touch $daemonFile
            echo '{ "insecure-registries":[] }' | jq '.' > /etc/docker/daemon.json
        fi
        echo -e "\nCurrent daemon.json"
        cat $daemonFile
        echo -e "\nWriting daemon.json"
        cat $daemonFile | jq '."insecure-registries" += ["'${localServer}':'${port}'"]'
        cat $daemonFile | jq '."insecure-registries" += ["'${localServer}':'${port}'"]' > /etc/docker/temp-daemon.json 
        rm $daemonFile && mv /etc/docker/temp-daemon.json $daemonFile
        echo -e "\nRestarting docker"
        systemctl restart docker
        echo -e "\nTrying to pull from repository"
        docker pull ${localServer}:${port}/$image
    fi
fi